services:
  order-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - "8080:8080"
    depends_on:
      - number-generate-service
      - order-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-service-db:5432/order-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always

  order-service-db:
    image: 'postgres:latest'
    container_name: order-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-service
    ports:
      - '5432:5432'
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always

  number-generate-service:
    build:
      context: ./number-generate-service
      dockerfile: Dockerfile
    container_name: number-generate-service
    ports:
      - "8081:8081"
    depends_on:
      - number-generate-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://number-generate-db:27017/number-generate
    restart: always

  number-generate-db:
    image: mongo:latest
    container_name: number-generate-db
    ports:
      - "27017:27017"