services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/order-service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always
  postgres-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-service
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  postgres-data:
