spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/number-generate

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              convert: TRACE
            repository: DEBUG

server:
  port: 8081